version: '3.5'

services:
  nginx:
    container_name: ${SERVICE_CONTAINER_NAME} # コンテナ名は他のdocker-compose内で名前が競合しないように変更すること
    image: nginx:1.19.0
    # ports:
    # - '${ACCESS_PORT}:80'       # ローカルマシンのポート/コンテナ内のポート
    depends_on:
      - php-fpm
    networks:
      - default
      - ${SHARED_NETWORK_NAME}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./workspace/:/var/www/html # ローカルディレクトリのファイル:コンテナ内のファイル

  php-fpm:
    image: php:7.2-fpm
    build: ./docker/php
    volumes:
      - ./workspace/:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_LOCAL_PORT}:3306' # ローカルマシンのポート/コンテナ内のポート
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.0.5
    # ports:
    #    - "6379:6379"
volumes:
  mysql-data:
networks:
  default:
    name: ${NETWORK_NAME}
  # ${SHARED_NETWORK_NAME}:
  shared-network:
    external: true