version: '3'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - '8080:80'       # ローカルマシンのポート/コンテナ内のポート
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./workspace/:/var/www/html
        # ローカルディレクトリのファイル:コンテナ内のファイル

  php-fpm:
    #image: php:7.2-fpm
    build: ./docker/php
    volumes:
      - ./workspace/:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: localapp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306" # ローカルマシンのポート/コンテナ内のポート
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.0.5
    # ports:
    #    - "6379:6379"
volumes:
  mysql-data:
